npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  fortawesome:
    npmRegistryServer: "https://registry.npmjs.org"
  atproto:
    npmRegistryServer: "https://registry.npmjs.org"
  gsap:
    npmRegistryServer: "https://registry.npmjs.org"
  types:
    npmRegistryServer: "https://registry.npmjs.org"
  vercel:
    npmRegistryServer: "https://registry.npmjs.org"
  eslint:
    npmRegistryServer: "https://registry.npmjs.org"
  stylistic:
    npmRegistryServer: "https://registry.npmjs.org"
  typescript-eslint:
    npmRegistryServer: "https://registry.npmjs.org" 