[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "rm -rf ~/.npm",
  "rm -rf ~/.npmrc",
  "npm cache clean --force",
  "npm config set registry https://registry.npmjs.org/",
  "npm config set @fortawesome:registry https://registry.npmjs.org/",
  "npm config set @atproto:registry https://registry.npmjs.org/",
  "npm config set @gsap:registry https://registry.npmjs.org/",
  "npm config set @types:registry https://registry.npmjs.org/",
  "npm config set @vercel:registry https://registry.npmjs.org/",
  "npm config set @eslint:registry https://registry.npmjs.org/",
  "npm config set @stylistic:registry https://registry.npmjs.org/",
  "npm config set @typescript-eslint:registry https://registry.npmjs.org/",
  "npm config set audit false",
  "npm config set fund false",
  "npm config list",
  "npm install --no-cache --registry https://registry.npmjs.org/"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 